#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${OMNIVOICE_ADMIN_USER}') THEN
        EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L', '${OMNIVOICE_ADMIN_USER}', '${OMNIVOICE_ADMIN_PASSWORD}');
    END IF;
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${OMNIVOICE_VIEWER_USER}') THEN
        EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L', '${OMNIVOICE_VIEWER_USER}', '${OMNIVOICE_VIEWER_PASSWORD}');
    END IF;
END
\$\$;

SELECT format('GRANT ALL PRIVILEGES ON DATABASE %I TO %I', current_database(), '${OMNIVOICE_ADMIN_USER}') \gexec
SELECT format('GRANT USAGE, CREATE ON SCHEMA public TO %I', '${OMNIVOICE_ADMIN_USER}') \gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), '${OMNIVOICE_VIEWER_USER}') \gexec
SELECT format('GRANT USAGE ON SCHEMA public TO %I', '${OMNIVOICE_VIEWER_USER}') \gexec
SELECT format('GRANT SELECT ON ALL TABLES IN SCHEMA public TO %I', '${OMNIVOICE_VIEWER_USER}') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO %I', '${OMNIVOICE_VIEWER_USER}') \gexec
SQL
